version: '3.6'
services:
    rabbitmq:
      image: rabbitmq:3-management
      ports:
      - "5672:5672"
      - "15672:15672"
      volumes:
        - ./rabbitmq-data:/var/lib/rabbitmq
      networks:
        - webhook_net

    mongo:
      image: mongo:4.4.5
      container_name: mongo
      ports:
      - "27017:27017"
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword
      networks:
        - webhook_net
      command: mongod --auth
      volumes:
        - type: bind
          source: ./mongo-data
          target: /data/db


    mongo-express:
      image: mongo-express:0.54.0
      container_name: mongo-express-container
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ports:
        - "8081:8081"
      depends_on:
        - mongo
      networks:
        - webhook_net


networks:
  webhook_net:
    driver: bridge

volumes:
  mongo-data:
