version: '3.6'
services:
    rabbitmq:
      image: rabbitmq:3-management
      ports:
      - "5672:5672"
      - "15672:15672"
      volumes:
        - ./rabbitmq-data:/var/lib/rabbitmq
      networks:
        - webhook_net

    mongo:
      image: mongo
      ports:
      - "27017:27017"
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
      networks:
        - webhook_net
      command: mongod --auth
      volumes:
        - ./mongo-data:/data/db

networks:
  webhook_net:
    driver: bridge
