version: '3.6'
services:
    rabbitmq:
      image: rabbitmq:3-management
      ports:
      - "5672:5672"
      - "15672:15672"
      volumes:
        - ./rabbitmq-data:/var/lib/rabbitmq
      networks:
        - webhook_net

    mongo:
      image: mongo:latest
      container_name: mongo
      ports:
        - "27017:27017"
      networks:
        - webhook_net
      volumes:
         - ./mongo-data:/data/db
      environment:
         - MONGO_INITDB_ROOT_USERNAME=root
         - MONGO_INITDB_ROOT_PASSWORD=password

    mongo-express:
      image: mongo-express:0.49.0
      container_name: mexpress
      environment:
          - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/


      links:
        - mongo
      ports:
        - 8081:8081
      networks:
        - webhook_net

networks:
  webhook_net:
    driver: bridge
